version: "3.7"

services:
    golang:
        build: 
            context: .
            dockerfile: ./compose/local/golang/Dockerfile
        image: golang_dev
        container_name: golang_dev
        volumes:
            - .:/wnc-final:z
        env_file:
            - ./.envs/.local/.golang
            - ./.envs/.local/.sqlite
        command: /start
        ports:
            - 8080:8080
        restart: always