version: "3.7"

services:
    golang:
        build:
            context: .
            dockerfile: ./compose/production/golang/Dockerfile
        image: golang
        env_file:
            - ./.envs/.production/.golang.sample
        depends_on:
            postgres:
                condition: service_healthy
        depends_on:
            - redis
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/ping/"]
        restart: always

    nginx:
        build:
            context: .
            dockerfile: ./compose/production/nginx/Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - golang