version: "3.7"

services:
    golang:
        build:
            context: .
            dockerfile: ./compose/production/golang/Dockerfile
        image: golang
        env_file:
            - ./.envs/.production/.golang
            - ./.envs/.production/.sqlite
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/ping/"]
        restart: always