app:
  name: 'wnc-final'
  version: '1.0.0'
  secret_key: 'dummy'

mail:
  confirm_email_template: './templates/transaction_confirm.html'
  confirm_email_subject: 'Confirm transaction'
  otp_timeout: '60s'

http:
  port: '8080'

logger:
  log_level: 'info'

db:
  pool_max: 90
