app:
  name: 'wnc-final'
  version: '1.0.0'
  secret_key: 'dummy'

mail:
  confirm_email_template: './templates/transaction_confirm.html'
  confirm_email_subject: 'Confirm transaction'
  otp_timeout: '300s'

http:
  port: '8080'

logger:
  log_level: 'info'

db:
  pool_max: 90

transaction_usecase:
  layout: '{{.receiver-bank-account-number}}{{.sender-bank-account-number}}{{.sender-name}}{{.amount}}{{.description}}{{.actor-type}}'
