// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TcMits/wnc-final/ent/admin"
	"github.com/TcMits/wnc-final/ent/predicate"
)

// AdminUpdate is the builder for updating Admin entities.
type AdminUpdate struct {
	config
	hooks    []Hook
	mutation *AdminMutation
}

// Where appends a list predicates to the AdminUpdate builder.
func (au *AdminUpdate) Where(ps ...predicate.Admin) *AdminUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUpdateTime sets the "update_time" field.
func (au *AdminUpdate) SetUpdateTime(t time.Time) *AdminUpdate {
	au.mutation.SetUpdateTime(t)
	return au
}

// SetJwtTokenKey sets the "jwt_token_key" field.
func (au *AdminUpdate) SetJwtTokenKey(s string) *AdminUpdate {
	au.mutation.SetJwtTokenKey(s)
	return au
}

// SetNillableJwtTokenKey sets the "jwt_token_key" field if the given value is not nil.
func (au *AdminUpdate) SetNillableJwtTokenKey(s *string) *AdminUpdate {
	if s != nil {
		au.SetJwtTokenKey(*s)
	}
	return au
}

// ClearJwtTokenKey clears the value of the "jwt_token_key" field.
func (au *AdminUpdate) ClearJwtTokenKey() *AdminUpdate {
	au.mutation.ClearJwtTokenKey()
	return au
}

// SetPassword sets the "password" field.
func (au *AdminUpdate) SetPassword(s string) *AdminUpdate {
	au.mutation.SetPassword(s)
	return au
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (au *AdminUpdate) SetNillablePassword(s *string) *AdminUpdate {
	if s != nil {
		au.SetPassword(*s)
	}
	return au
}

// ClearPassword clears the value of the "password" field.
func (au *AdminUpdate) ClearPassword() *AdminUpdate {
	au.mutation.ClearPassword()
	return au
}

// SetUsername sets the "username" field.
func (au *AdminUpdate) SetUsername(s string) *AdminUpdate {
	au.mutation.SetUsername(s)
	return au
}

// SetFirstName sets the "first_name" field.
func (au *AdminUpdate) SetFirstName(s string) *AdminUpdate {
	au.mutation.SetFirstName(s)
	return au
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (au *AdminUpdate) SetNillableFirstName(s *string) *AdminUpdate {
	if s != nil {
		au.SetFirstName(*s)
	}
	return au
}

// ClearFirstName clears the value of the "first_name" field.
func (au *AdminUpdate) ClearFirstName() *AdminUpdate {
	au.mutation.ClearFirstName()
	return au
}

// SetLastName sets the "last_name" field.
func (au *AdminUpdate) SetLastName(s string) *AdminUpdate {
	au.mutation.SetLastName(s)
	return au
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (au *AdminUpdate) SetNillableLastName(s *string) *AdminUpdate {
	if s != nil {
		au.SetLastName(*s)
	}
	return au
}

// ClearLastName clears the value of the "last_name" field.
func (au *AdminUpdate) ClearLastName() *AdminUpdate {
	au.mutation.ClearLastName()
	return au
}

// SetIsActive sets the "is_active" field.
func (au *AdminUpdate) SetIsActive(b bool) *AdminUpdate {
	au.mutation.SetIsActive(b)
	return au
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (au *AdminUpdate) SetNillableIsActive(b *bool) *AdminUpdate {
	if b != nil {
		au.SetIsActive(*b)
	}
	return au
}

// ClearIsActive clears the value of the "is_active" field.
func (au *AdminUpdate) ClearIsActive() *AdminUpdate {
	au.mutation.ClearIsActive()
	return au
}

// Mutation returns the AdminMutation object of the builder.
func (au *AdminUpdate) Mutation() *AdminMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AdminUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	au.defaults()
	if len(au.hooks) == 0 {
		if err = au.check(); err != nil {
			return 0, err
		}
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdminMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = au.check(); err != nil {
				return 0, err
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AdminUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AdminUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AdminUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AdminUpdate) defaults() {
	if _, ok := au.mutation.UpdateTime(); !ok {
		v := admin.UpdateDefaultUpdateTime()
		au.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AdminUpdate) check() error {
	if v, ok := au.mutation.Password(); ok {
		if err := admin.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Admin.password": %w`, err)}
		}
	}
	if v, ok := au.mutation.Username(); ok {
		if err := admin.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Admin.username": %w`, err)}
		}
	}
	if v, ok := au.mutation.FirstName(); ok {
		if err := admin.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Admin.first_name": %w`, err)}
		}
	}
	if v, ok := au.mutation.LastName(); ok {
		if err := admin.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "Admin.last_name": %w`, err)}
		}
	}
	return nil
}

func (au *AdminUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   admin.Table,
			Columns: admin.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: admin.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UpdateTime(); ok {
		_spec.SetField(admin.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := au.mutation.JwtTokenKey(); ok {
		_spec.SetField(admin.FieldJwtTokenKey, field.TypeString, value)
	}
	if au.mutation.JwtTokenKeyCleared() {
		_spec.ClearField(admin.FieldJwtTokenKey, field.TypeString)
	}
	if value, ok := au.mutation.Password(); ok {
		_spec.SetField(admin.FieldPassword, field.TypeString, value)
	}
	if au.mutation.PasswordCleared() {
		_spec.ClearField(admin.FieldPassword, field.TypeString)
	}
	if value, ok := au.mutation.Username(); ok {
		_spec.SetField(admin.FieldUsername, field.TypeString, value)
	}
	if value, ok := au.mutation.FirstName(); ok {
		_spec.SetField(admin.FieldFirstName, field.TypeString, value)
	}
	if au.mutation.FirstNameCleared() {
		_spec.ClearField(admin.FieldFirstName, field.TypeString)
	}
	if value, ok := au.mutation.LastName(); ok {
		_spec.SetField(admin.FieldLastName, field.TypeString, value)
	}
	if au.mutation.LastNameCleared() {
		_spec.ClearField(admin.FieldLastName, field.TypeString)
	}
	if value, ok := au.mutation.IsActive(); ok {
		_spec.SetField(admin.FieldIsActive, field.TypeBool, value)
	}
	if au.mutation.IsActiveCleared() {
		_spec.ClearField(admin.FieldIsActive, field.TypeBool)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AdminUpdateOne is the builder for updating a single Admin entity.
type AdminUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminMutation
}

// SetUpdateTime sets the "update_time" field.
func (auo *AdminUpdateOne) SetUpdateTime(t time.Time) *AdminUpdateOne {
	auo.mutation.SetUpdateTime(t)
	return auo
}

// SetJwtTokenKey sets the "jwt_token_key" field.
func (auo *AdminUpdateOne) SetJwtTokenKey(s string) *AdminUpdateOne {
	auo.mutation.SetJwtTokenKey(s)
	return auo
}

// SetNillableJwtTokenKey sets the "jwt_token_key" field if the given value is not nil.
func (auo *AdminUpdateOne) SetNillableJwtTokenKey(s *string) *AdminUpdateOne {
	if s != nil {
		auo.SetJwtTokenKey(*s)
	}
	return auo
}

// ClearJwtTokenKey clears the value of the "jwt_token_key" field.
func (auo *AdminUpdateOne) ClearJwtTokenKey() *AdminUpdateOne {
	auo.mutation.ClearJwtTokenKey()
	return auo
}

// SetPassword sets the "password" field.
func (auo *AdminUpdateOne) SetPassword(s string) *AdminUpdateOne {
	auo.mutation.SetPassword(s)
	return auo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (auo *AdminUpdateOne) SetNillablePassword(s *string) *AdminUpdateOne {
	if s != nil {
		auo.SetPassword(*s)
	}
	return auo
}

// ClearPassword clears the value of the "password" field.
func (auo *AdminUpdateOne) ClearPassword() *AdminUpdateOne {
	auo.mutation.ClearPassword()
	return auo
}

// SetUsername sets the "username" field.
func (auo *AdminUpdateOne) SetUsername(s string) *AdminUpdateOne {
	auo.mutation.SetUsername(s)
	return auo
}

// SetFirstName sets the "first_name" field.
func (auo *AdminUpdateOne) SetFirstName(s string) *AdminUpdateOne {
	auo.mutation.SetFirstName(s)
	return auo
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (auo *AdminUpdateOne) SetNillableFirstName(s *string) *AdminUpdateOne {
	if s != nil {
		auo.SetFirstName(*s)
	}
	return auo
}

// ClearFirstName clears the value of the "first_name" field.
func (auo *AdminUpdateOne) ClearFirstName() *AdminUpdateOne {
	auo.mutation.ClearFirstName()
	return auo
}

// SetLastName sets the "last_name" field.
func (auo *AdminUpdateOne) SetLastName(s string) *AdminUpdateOne {
	auo.mutation.SetLastName(s)
	return auo
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (auo *AdminUpdateOne) SetNillableLastName(s *string) *AdminUpdateOne {
	if s != nil {
		auo.SetLastName(*s)
	}
	return auo
}

// ClearLastName clears the value of the "last_name" field.
func (auo *AdminUpdateOne) ClearLastName() *AdminUpdateOne {
	auo.mutation.ClearLastName()
	return auo
}

// SetIsActive sets the "is_active" field.
func (auo *AdminUpdateOne) SetIsActive(b bool) *AdminUpdateOne {
	auo.mutation.SetIsActive(b)
	return auo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (auo *AdminUpdateOne) SetNillableIsActive(b *bool) *AdminUpdateOne {
	if b != nil {
		auo.SetIsActive(*b)
	}
	return auo
}

// ClearIsActive clears the value of the "is_active" field.
func (auo *AdminUpdateOne) ClearIsActive() *AdminUpdateOne {
	auo.mutation.ClearIsActive()
	return auo
}

// Mutation returns the AdminMutation object of the builder.
func (auo *AdminUpdateOne) Mutation() *AdminMutation {
	return auo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AdminUpdateOne) Select(field string, fields ...string) *AdminUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Admin entity.
func (auo *AdminUpdateOne) Save(ctx context.Context) (*Admin, error) {
	var (
		err  error
		node *Admin
	)
	auo.defaults()
	if len(auo.hooks) == 0 {
		if err = auo.check(); err != nil {
			return nil, err
		}
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdminMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = auo.check(); err != nil {
				return nil, err
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, auo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Admin)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AdminMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AdminUpdateOne) SaveX(ctx context.Context) *Admin {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AdminUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AdminUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AdminUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdateTime(); !ok {
		v := admin.UpdateDefaultUpdateTime()
		auo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AdminUpdateOne) check() error {
	if v, ok := auo.mutation.Password(); ok {
		if err := admin.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Admin.password": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Username(); ok {
		if err := admin.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Admin.username": %w`, err)}
		}
	}
	if v, ok := auo.mutation.FirstName(); ok {
		if err := admin.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Admin.first_name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.LastName(); ok {
		if err := admin.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`ent: validator failed for field "Admin.last_name": %w`, err)}
		}
	}
	return nil
}

func (auo *AdminUpdateOne) sqlSave(ctx context.Context) (_node *Admin, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   admin.Table,
			Columns: admin.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: admin.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Admin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, admin.FieldID)
		for _, f := range fields {
			if !admin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != admin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UpdateTime(); ok {
		_spec.SetField(admin.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := auo.mutation.JwtTokenKey(); ok {
		_spec.SetField(admin.FieldJwtTokenKey, field.TypeString, value)
	}
	if auo.mutation.JwtTokenKeyCleared() {
		_spec.ClearField(admin.FieldJwtTokenKey, field.TypeString)
	}
	if value, ok := auo.mutation.Password(); ok {
		_spec.SetField(admin.FieldPassword, field.TypeString, value)
	}
	if auo.mutation.PasswordCleared() {
		_spec.ClearField(admin.FieldPassword, field.TypeString)
	}
	if value, ok := auo.mutation.Username(); ok {
		_spec.SetField(admin.FieldUsername, field.TypeString, value)
	}
	if value, ok := auo.mutation.FirstName(); ok {
		_spec.SetField(admin.FieldFirstName, field.TypeString, value)
	}
	if auo.mutation.FirstNameCleared() {
		_spec.ClearField(admin.FieldFirstName, field.TypeString)
	}
	if value, ok := auo.mutation.LastName(); ok {
		_spec.SetField(admin.FieldLastName, field.TypeString, value)
	}
	if auo.mutation.LastNameCleared() {
		_spec.ClearField(admin.FieldLastName, field.TypeString)
	}
	if value, ok := auo.mutation.IsActive(); ok {
		_spec.SetField(admin.FieldIsActive, field.TypeBool, value)
	}
	if auo.mutation.IsActiveCleared() {
		_spec.ClearField(admin.FieldIsActive, field.TypeBool)
	}
	_node = &Admin{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
